/**
 * Created by Alexandra on 14.06.17.
 */

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_DISPLAYED_PRODUCTS_SUCCESS = 'GET_DISPLAYED_PRODUCTS_SUCCESS';
export const FILTER_BY_SIZE = 'FILTER_BY_SIZE';
export const FILTER_BY_INGREDIENTS = 'FILTER_BY_INGREDIENTS';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const INCREASE_NUMBER_PRODUCT = 'INCREASE_NUMBER_PRODUCT';

export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
export const GET_TOTAL_PRICE = 'GET_TOTAL_PRICE';
export const SEND_ORDER_FORM = 'SEND_ORDER_FORM';

export const UPDATE_INPUT_NAME = 'UPDATE_INPUT_NAME';
export const UPDATE_INPUT_EMAIL = 'UPDATE_INPUT_EMAIL';
export const UPDATE_INPUT_PHONE = 'UPDATE_INPUT_PHONE';
export const UPDATE_INPUT_CITY = 'UPDATE_INPUT_CITY';
export const UPDATE_INPUT_STREET = 'UPDATE_INPUT_STREET';
export const UPDATE_INPUT_HOUSE = 'UPDATE_INPUT_HOUSE';
export const UPDATE_INPUT_APARTMENT = 'UPDATE_INPUT_APARTMENT';
export const UPDATE_INPUT_ACCESS = 'UPDATE_INPUT_ACCESS';
export const UPDATE_INPUT_FLOOR = 'UPDATE_INPUT_FLOOR';
export const UPDATE_INPUT_ADDITIONAL_INFORMATION =
	'UPDATE_INPUT_ADDITIONAL_INFORMATION';
export const CHANGE_PAYMENT_THE_INTERNET = 'CHANGE_PAYMENT_THE_INTERNET';
export const CHECK_CUT_PIZZA = 'CHECK_CUT_PIZZA';