/**
 * Created by Alexandra on 14.06.17.
 */

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_DISPLAYED_PRODUCTS = 'GET_DISPLAYED_PRODUCTS';
export const FILTER_BY_SIZE = 'FILTER_BY_SIZE';
export const FILTER_BY_INGREDIENTS = 'FILTER_BY_INGREDIENTS';
export const CHANGE_PRICE_FROM = 'CHANGE_PRICE_FROM';
export const CHANGE_PRICE_TO = 'CHANGE_PRICE_TO';
export const FILTER_BY_PRICE = 'FILTER_BY_PRICE';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const INCREASE_NUMBER_PRODUCT = 'INCREASE_NUMBER_PRODUCT';

export const GET_CART = 'GET_CART';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
export const GET_TOTAL_PRICE = 'GET_TOTAL_PRICE';

// ORDER FORM
export const UPDATE_INPUT_NAME_ORDER_FORM = 'UPDATE_INPUT_NAME_ORDER_FORM';
export const UPDATE_INPUT_EMAIL_ORDER_FORM = 'UPDATE_INPUT_EMAIL_ORDER_FORM';
export const UPDATE_INPUT_PHONE_ORDER_FORM = 'UPDATE_INPUT_PHONE_ORDER_FORM';
export const UPDATE_INPUT_CITY_ORDER_FORM = 'UPDATE_INPUT_CITY_ORDER_FORM';
export const UPDATE_INPUT_STREET_ORDER_FORM = 'UPDATE_INPUT_STREET_ORDER_FORM';
export const UPDATE_INPUT_HOUSE_ORDER_FORM = 'UPDATE_INPUT_HOUSE_ORDER_FORM';
export const UPDATE_INPUT_APARTMENT_ORDER_FORM =
	'UPDATE_INPUT_APARTMENT_ORDER_FORM';
export const UPDATE_INPUT_ACCESS_ORDER_FORM = 'UPDATE_INPUT_ACCESS_ORDER_FORM';
export const UPDATE_INPUT_FLOOR_ORDER_FORM = 'UPDATE_INPUT_FLOOR_ORDER_FORM';
export const UPDATE_INPUT_ADDITIONAL_INFORMATION_ORDER_FORM =
	'UPDATE_INPUT_ADDITIONAL_INFORMATION';
export const CHANGE_PAYMENT_THE_INTERNET_ORDER_FORM =
	'CHANGE_PAYMENT_THE_INTERNET_ORDER_FORM';
export const CHECK_CUT_PIZZA_ORDER_FORM = 'CHECK_CUT_PIZZA_ORDER_FORM';
export const SEND_ORDER_FORM = 'SEND_ORDER_FORM';

// CONTACT US FORM
export const UPDATE_INPUT_NAME_CONTACT_US_FORM =
	'UPDATE_INPUT_NAME_CONTACT_US_FORM';
export const UPDATE_INPUT_EMAIL_CONTACT_US_FORM =
	'UPDATE_INPUT_EMAIL_CONTACT_US_FORM';
export const UPDATE_INPUT_QUERY_CONTACT_US_FORM =
	'UPDATE_INPUT_QUERY_CONTACT_US_FORM';
export const SEND_CONTACT_US_FORM = 'SEND_CONTACT_US_FORM';

// LOGIN FORM
export const UPDATE_INPUT_NAME_LOGIN_FORM = 'UPDATE_INPUT_NAME_LOGIN_FORM';
export const UPDATE_INPUT_PASSWORD_LOGIN_FORM =
	'UPDATE_INPUT_PASSWORD_LOGIN_FORM';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';

// SIGN_UP FROM
export const UPDATE_INPUT_NAME_SIGN_UP_FORM = 'UPDATE_INPUT_NAME_SIGN_UP_FORM';
export const UPDATE_INPUT_EMAIL_SIGN_UP_FORM =
	'UPDATE_INPUT_EMAIL_SIGN_UP_FORM';
export const UPDATE_INPUT_PASSWORD_SIGN_UP_FORM =
	'UPDATE_INPUT_PASSWORD_SIGN_UP_FORM';
export const UPDATE_INPUT_PHONE_SIGN_UP_FORM =
	'UPDATE_INPUT_PHONE_SIGN_UP_FORM';
export const UPDATE_INPUT_CITY_SIGN_UP_FORM = 'UPDATE_INPUT_CITY_SIGN_UP_FORM';
export const UPDATE_INPUT_STREET_SIGN_UP_FORM =
	'UPDATE_INPUT_STREET_SIGN_UP_FORM';
export const UPDATE_INPUT_HOUSE_SIGN_UP_FORM =
	'UPDATE_INPUT_HOUSE_SIGN_UP_FORM';
export const UPDATE_INPUT_APARTMENT_SIGN_UP_FORM =
	'UPDATE_INPUT_APARTMENT_SIGN_UP_FORM';
export const UPDATE_INPUT_ACCESS_SIGN_UP_FORM =
	'UPDATE_INPUT_ACCESS_SIGN_UP_FORM';
export const UPDATE_INPUT_FLOOR_SIGN_UP_FORM =
	'UPDATE_INPUT_FLOOR_SIGN_UP_FORM';
export const SIGN_UP_FORM = 'SIGN_UP_FORM';
export const GET_REGISTERED_USERS_SUCCESS = 'GET_REGISTERED_USERS_SUCCESS';
export const GET_REGISTERED_USERS_FAILURE = 'GET_REGISTERED_USERS_FAILURE';
