/**
 * Created by Alexandra on 14.06.17.
 */

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const FILTER_BY_SIZE = 'FILTER_BY_SIZE';
export const FILTER_BY_INGREDIENTS = 'FILTER_BY_INGREDIENTS';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';